### ISSUE TITLE
handleActions is broken

### ISSUE THREAD

**Issue by ericdevries** [reduxactions/redux-actions#232]
After updating redux actions by accident, I found the following issue
https://github.com/lodash/lodash/issues/3271

Turns out the change that broke it is inside redux-actions. The offending line is https://github.com/acdlite/redux-actions/blob/758ad1004993f59bb826aa4b365d038239797cb0/src/handleActions.js#L13

The flattenedReducerMap iteratets over all the Reflect.ownKeys() values, which contains a curious object symbol that is set by lodash. 

I suggest switching over to Object.keys, unless you have a specific reason for also wanting to iterate over symbols

**Comment by tuneZola** [comment]
+1, 
@ericdevries do you know the last working version?

**Comment by yangmillstheory** [comment]
Sounds good; care to submit a PR?

**Comment by mkascel** [comment]
@ericdevries I'm evaluating this lib for possible inclusion into a project; the linked lodash issue you created was closed with the author saying it might be due to local setup (babel plugin or the like).  Can you confirm if this is still an issue or not?  And if it is due to a babel plugin/version of a lib it would be good to know.

**Comment by ericdevries** [comment]
I spent a complete day finding out what it was, and after a complete re-install and reboot the problem disappeared, so I would like to think it was an error in my local setup.
