### ISSUE TITLE
Async action can't be handle when use combineActions and async middleware

### ISSUE THREAD

**Issue by NE-SmallTown** [reduxactions/redux-actions#258]
In the [example](https://redux-actions.js.org/docs/api/combineActions.html):

```
const { increment, decrement } = createActions({
  INCREMENT: amount => ({ amount }),
  DECREMENT: amount => ({ amount: -amount })
});

const reducer = handleActions({
  [combineActions(increment, decrement)](state, { payload: { amount } }) {
    return { ...state, counter: state.counter + amount };
  }
}, { counter: 10 });
```

But if our action creator is async(e.g. `INCREMENT: () => fetch('foo')`) and we use some middlewares like `redux-promise-middleware`, the `INCREMENT` will be split to three actions like `INCREMENT__PENDING`, `INCREMENT__FULFILLED`, `INCREMENT__REJECTED`, but the `combineActions` seems can't handle this scenario, it just can handle the `INCREMENT` action type

**Comment by mslipper** [comment]
Hi @NE-SmallTown,

I can look into this in a few days - I just got access to the repo and will start maintaining it going forward. I need some time to get an overview of the code and the roadmap first. Does this work for you?

**Comment by NE-SmallTown** [comment]
Don't worry, it's fine :)

**Comment by mslipper** [comment]
Hi @NE-SmallTown,

I had a chance to look over the code. Here's what I suggest you do. Since `redux-actions` isn't aware of every middleware setup, try creating a utility function that maps the postfixed action names generated by your middleware to the same action creator. Something like this might work:

```js
const states = ['PENDING', 'FULFILLED', 'REJECTED'];

function asyncActions(actions) {
  return Object.keys(actions).reduce((acc, curr) => {
    const creator = actions[curr];
    acc[curr] = creator;
    states.forEach((state) => {
      acc[`${curr}__${state}`] = creator;
    });
    return acc;
  }, {});
}
```

Then, in your action creator, you'd call `createActions` like this:

```js
const { incremenfFulfilled } = createActions({
  ...asyncActions({
    INCREMENT: amount => ({ amount })
  },
  NOT_ASYC: () => 'Yay'
});
```

Your reducer can then handle the fulfilled, rejected, or pending scenarios however it chooses. Note that the `camelCase` lib will automatically camel case names like INCREMENT_FULFILLED to `incrementFulfilled`, so you can use the destructuring idiom described in the docs to pass actions to `combineActions`.

**Comment by NE-SmallTown** [comment]
Thanks, looks good. I will try
